name: Firebase Deploy

on:
  push:
    branches:
      - master
      - testing
jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'functions/package-lock.json'
      
      - name: Install dependencies
        run: cd functions && npm ci
      
      - name: Build
        run: cd functions && npm run build
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: |
          # Set project ID based on branch
          PROJECT_ID=${{ github.ref == 'refs/heads/master' && 'structify-chris-cole' || 'chris-cole-test' }}
          
          # Create service account key file
          echo '${{ github.ref == 'refs/heads/master' && secrets.FIREBASE_SERVICE_ACCOUNT_LIVE || secrets.FIREBASE_SERVICE_ACCOUNT_TESTING }}' > /tmp/service-account.json
          
          # Set GOOGLE_APPLICATION_CREDENTIALS environment variable
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/service-account.json
          
          # Deploy using Firebase CLI with --force flag to bypass checks
          firebase deploy --only functions --project $PROJECT_ID --non-interactive --force
          
          # Clean up
          rm /tmp/service-account.json
      
      - name: Log deployment info
        run: |
          echo "Deployed to project: ${{ github.ref == 'refs/heads/master' && 'structify-chris-cole' || 'chris-cole-test' }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"